// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/solar-dashboard/AlertPanel.tsx": () => import("../components/mockups/solar-dashboard/AlertPanel.tsx"),
  "./components/mockups/solar-dashboard/Dashboard.tsx": () => import("../components/mockups/solar-dashboard/Dashboard.tsx"),
  "./components/mockups/solar-dashboard/ForecastChart.tsx": () => import("../components/mockups/solar-dashboard/ForecastChart.tsx"),
  "./components/mockups/solar-dashboard/StatusBar.tsx": () => import("../components/mockups/solar-dashboard/StatusBar.tsx"),
  "./components/mockups/solar-dashboard/SunVisualization.tsx": () => import("../components/mockups/solar-dashboard/SunVisualization.tsx"),
  "./components/mockups/solar-dashboard/TelemetryPanel.tsx": () => import("../components/mockups/solar-dashboard/TelemetryPanel.tsx")
};
