// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/solar-dashboard/AlertPanel.tsx": () => import("../components/mockups/solar-dashboard/AlertPanel.tsx"),
  "./components/mockups/solar-dashboard/Dashboard.tsx": () => import("../components/mockups/solar-dashboard/Dashboard.tsx"),
  "./components/mockups/solar-dashboard/FlareEventLog.tsx": () => import("../components/mockups/solar-dashboard/FlareEventLog.tsx"),
  "./components/mockups/solar-dashboard/ForecastChart.tsx": () => import("../components/mockups/solar-dashboard/ForecastChart.tsx"),
  "./components/mockups/solar-dashboard/ForecastPanel.tsx": () => import("../components/mockups/solar-dashboard/ForecastPanel.tsx"),
  "./components/mockups/solar-dashboard/HistoricalTimeline.tsx": () => import("../components/mockups/solar-dashboard/HistoricalTimeline.tsx"),
  "./components/mockups/solar-dashboard/NowcastPanel.tsx": () => import("../components/mockups/solar-dashboard/NowcastPanel.tsx"),
  "./components/mockups/solar-dashboard/StatusBar.tsx": () => import("../components/mockups/solar-dashboard/StatusBar.tsx"),
  "./components/mockups/solar-dashboard/SunVisualization.tsx": () => import("../components/mockups/solar-dashboard/SunVisualization.tsx"),
  "./components/mockups/solar-dashboard/TelemetryPanel.tsx": () => import("../components/mockups/solar-dashboard/TelemetryPanel.tsx"),
  "./components/mockups/solar-dashboard/XRayLightCurves.tsx": () => import("../components/mockups/solar-dashboard/XRayLightCurves.tsx")
};
